kind: pipeline
type: docker
name: default

steps:
- name: backend
  image: node:12.18.0
  environment:
    DATABASE_URL: "postgresql://postgres:@database:5432/formataja?schema=public"
  depends_on:
  - sql
  - database
  commands:
  - sleep 15
  - npm i
  - npm run test

steps:
- name: sql
  image: postgres
  depends_on:
  - database
  commands:
  - psql -U postgres -d test -h database
  # - psql -h database -U postgres -d formataja -a -f ./database/database.sql

services:
- name: database
  image: postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_DB: formataja
