kind: pipeline
type: docker
name: default

steps:
- name: backend
  image: node:12.18.0
  environment:
    DRONE_STAGE_DEPENDS_ON
    DATABASE_URL: "postgresql://postgres:123123@database:5432/formataja?schema=public"
  depends_on:
  - sql
  commands:
  - sleep 15
  - npm i
  - npm run test
  when:
    event:
      include:
      - pull_request
      - push
    branch:
      include:
      - develop
      exclude:
      - master

steps:
- name: sql
  image: postgres
  depends_on:
  - database
  commands:
  - sleep 10
  - psql -U postgres -x 123123 -d formataja -a -f database/database.sql

services:
- name: database
  image: postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_DB: formataja
    POSTGRES_PASSWORD: 123123
