kind: pipeline
type: docker
name: node

platform:
  arch: amd64

steps:
  - name: backend
    image: node:12.18.0
    environment:
      DATABASE_URL: 127.0.0.1
    depends_on:
      - database
    commands:
      - npm i
      - npx prisma generate
      - npx jest --runInBand --detectOpenHandles

services:
  - name: database
    image: postgres
    detach: true
    ports:
      - 5432
    environment:
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: formataja
