version: '3.1'

services:

  db:
    image: postgres
    volumes:
      - "./database.sql:/database.sql"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: formataja

  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: 'mckatoo@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: '123123'
